stages:
  
  data_ingestion:
    cmd: python -m src.cancer_clf.pipelines.stage_01_data_ingestion
    deps:
      - src/cancer_clf/pipelines/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chest-CT-Scan-data
    
  prepare_base_model:
    cmd: python -m src.cancer_clf.pipelines.stage_02_prepare_base_model
    deps:
      - src/cancer_clf/pipelines/stage_02_prepare_base_model.py
      - config/config.yaml
      - params.yaml
    params: 
      - IMAGE_SIZE
      - CLASSES
      - WEIGHTS
      - INCLUDE_TOP
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model
  
  hyperparameter_tuning:
    cmd: python -m src.cancer_clf.pipelines.stage_03_hyperparameter_tuning
    deps:
      - src/cancer_clf/pipelines/stage_03_hyperparameter_tuning.py
      - artifacts/data_ingestion/Chest-CT-Scan-data
      - params.yaml
    params:
      - IMAGE_SIZE
      - SEED
    outs:
      - artifacts/hyperparameter_tuning/best_params.json
  
  training:
    cmd: python -m src.cancer_clf.pipelines.stage_04_model_trainer
    deps:
      - src/cancer_clf/pipelines/stage_04_model_trainer.py
      - artifacts/data_ingestion/Chest-CT-Scan-data/train
      - artifacts/data_ingestion/Chest-CT-Scan-data/test
      - artifacts/prepare_base_model
      - artifacts/hyperparameter_tuning/best_params.json
      - params.yaml
    params:
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
      - IMAGE_SIZE
      - SEED
    outs:
      - artifacts/training/model_best_hparams.pt
  
  evaluation:
    cmd: python -m src.cancer_clf.pipelines.stage_05_model_evaluation
    deps:
      - src/cancer_clf/pipelines/stage_05_model_evaluation.py
      - artifacts/data_ingestion/Chest-CT-Scan-data/test
      - params.yaml
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
      - SEED
    metrics:
      - test_scores.json:
          cache: false 
