AUGMENTATION: True 
IMAGE_SIZE: [224,224]
CHANNELS: 3
BATCH_SIZE: 8
INCLUDE_TOP: False # False: Replace the classifier head, True: Use original FC layers
EPOCHS: 50 # Use more epochs
CLASSES: 1 
WEIGHTS: imagenet
LEARNING_RATE: 0.00001
SEED: 42
